version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      
    ports:
      - 9200:9200
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 30s
  
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    # command: bash -c "cd app/app && python parsing.py && python modelling.py && python indexing.py && python retrieval.py"
    container_name: question_answering
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - elasticsearch