# Use the official Elasticsearch image as the base image
FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.0

# Set environment variables (customize as needed)
ENV "xpack.security.enabled"="false"
ENV "discovery.type"="single-node"

# Expose the ports for Elasticsearch (if needed)
EXPOSE 9200 9300